# This is a basic workflow to help you get started with Actions

name: BuildRelease_caller

env:
  JenkinsUrl: http://jenkins1.sherb.vantrix.com:8080

# Controls when the workflow will run 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      gitRev:
        description: 'git rev or tag to build. default: head of current branch'
        required: false
        default: ''
      debVersion:
        description: 'Version tag'
        required: false
        default: ''
      doAptGet: 
        description: 'Apt get'
        type: boolean
        default: true
      doCheckout: 
        description: 'code Checkout'
        type: boolean
        default: true
      doBuild: 
        description: 'Build'
        type: boolean
        default: true
      buildOptions:
        description: 'option to pass to buildall script (ex: "--build ltrx")'
        required: false
        default: '-v'
      doDebian: 
        description: 'Generate Debian'
        type: boolean
        default: true
      doDebNexusUpload: 
        description: 'Send the .deb to Nexus'
        type: boolean
        default: true
      doDebJenkinsUpload: 
        description: 'Send the .deb to Jenkins'
        type: boolean
        default: true
      doJenkinsRegression: 
        description: 'Start regression on Jenkins'
        type: boolean
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  set_env:
    # name: build caller
    runs-on: self-hosted

    steps:
    - name: HERE1
      run: echo "HERE1"
      
    - name: HERE2
      run: |
          echo "HERE2"
    outputs:
      config_path: TEST_12345

  show_env:
    runs-on: self-hosted
    needs: [set_env]
    steps:
    - name: Show ENV
      run: echo "SHow env ${{ needs.set_env.outputs.config_path }}"

  build_post:
    needs: [set_env]
    name: ALLO
    # job calling other workflow can't use steps in them
    uses: ./.github/workflows/nightbuild_common.yml
    with:
      config_path: ${{ needs.set_env.outputs.config_path }}
      #env: ${{ github.event.inputs.environment }}
      #secrets: inherit



